ALTER TABLE admin_action_log
MODIFY COLUMN action_type ENUM(
    'MEMBER_BANNED',
    'MEMBER_UNBANNED',
    'REPORT_RESOLVED',
    'MEMBER_PROMOTED_TO_ADMIN',
    'MEMBER_DEMOTED_TO_USER',
    'MEMBER_DELETED'
) NOT NULL;
